/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.github.projetolp2.view;

/**
 *
 * @author Guerreiro 3.0
 */
public class TelaConsultarSDI extends javax.swing.JPanel {

    /**
     * Creates new form TelaConsultarCadastroSDI
     */
    public TelaConsultarSDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_Consulta = new javax.swing.ButtonGroup();
        jScrollPane_Tabela = new javax.swing.JScrollPane();
        jTable_Tabela = new javax.swing.JTable();
        jTextField_Pesquisa = new javax.swing.JTextField();
        jButton_Pesquisar = new javax.swing.JButton();
        jLabel_Descricao = new javax.swing.JLabel();
        jScrollPane_Descricao = new javax.swing.JScrollPane();
        jTextArea_Descricao_Consulta = new javax.swing.JTextArea();
        jLabel_PesquisarPor = new javax.swing.JLabel();
        jRadioButton_Placa = new javax.swing.JRadioButton();
        jRadioButton_Modelo = new javax.swing.JRadioButton();
        jRadioButton_Proprietario = new javax.swing.JRadioButton();
        jLabel_DigiteAqui = new javax.swing.JLabel();

        jTable_Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Proprietário", "Telefone", "Placa", "Modelo", "Marca", "Ano", "Descrição"
            }
        ));
        jScrollPane_Tabela.setViewportView(jTable_Tabela);

        jTextField_Pesquisa.addActionListener(this::jTextField_PesquisaActionPerformed);

        jButton_Pesquisar.setText("Pesquisar");
        jButton_Pesquisar.addActionListener(this::jButton_PesquisarActionPerformed);

        jLabel_Descricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Descricao.setText("Descrição:");

        jTextArea_Descricao_Consulta.setColumns(20);
        jTextArea_Descricao_Consulta.setRows(5);
        jScrollPane_Descricao.setViewportView(jTextArea_Descricao_Consulta);

        jLabel_PesquisarPor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_PesquisarPor.setText("Pesquisar por:");

        buttonGroup_Consulta.add(jRadioButton_Placa);
        jRadioButton_Placa.setText("Placa");

        buttonGroup_Consulta.add(jRadioButton_Modelo);
        jRadioButton_Modelo.setText("Modelo");
        jRadioButton_Modelo.addActionListener(this::jRadioButton_ModeloActionPerformed);

        buttonGroup_Consulta.add(jRadioButton_Proprietario);
        jRadioButton_Proprietario.setText("Proprietário");

        jLabel_DigiteAqui.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_DigiteAqui.setText("Digite aqui:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_Tabela)
                    .addComponent(jScrollPane_Descricao)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Descricao)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_PesquisarPor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton_Placa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton_Modelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton_Proprietario))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_DigiteAqui)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 265, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_PesquisarPor)
                    .addComponent(jRadioButton_Placa)
                    .addComponent(jRadioButton_Modelo)
                    .addComponent(jRadioButton_Proprietario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_DigiteAqui)
                    .addComponent(jTextField_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_Tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_PesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PesquisaActionPerformed
 
    }//GEN-LAST:event_jTextField_PesquisaActionPerformed

    private void jRadioButton_ModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ModeloActionPerformed
     
    }//GEN-LAST:event_jRadioButton_ModeloActionPerformed

    private void jButton_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PesquisarActionPerformed
/*
        ResultSet rs = null;

        String pesquisa = jTextField_Pesquisa.getText();

        if (jRadioButton_Placa.isSelected()) {
            
        } 
        else if (jRadioButton_Modelo.isSelected()) {
           
        } 
        else if (jRadioButton_Proprietario.isSelected()) {
            
        }

        DefaultTableModel modelo =
                (DefaultTableModel) jTable_Tabela.getModel();

        modelo.setRowCount(0);

        while (rs.next()) {
            modelo.addRow(new Object[]{
                rs.getString("codigo"),
                rs.getString("proprietario"),
                rs.getString("telefone"),
                rs.getString("placa"),
                rs.getString("modelo"),
                rs.getString("marca"),
                rs.getString("ano"),
                rs.getString("descricao")
            });
        }
*/
    }//GEN-LAST:event_jButton_PesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_Consulta;
    private javax.swing.JButton jButton_Pesquisar;
    private javax.swing.JLabel jLabel_Descricao;
    private javax.swing.JLabel jLabel_DigiteAqui;
    private javax.swing.JLabel jLabel_PesquisarPor;
    private javax.swing.JRadioButton jRadioButton_Modelo;
    private javax.swing.JRadioButton jRadioButton_Placa;
    private javax.swing.JRadioButton jRadioButton_Proprietario;
    private javax.swing.JScrollPane jScrollPane_Descricao;
    private javax.swing.JScrollPane jScrollPane_Tabela;
    private javax.swing.JTable jTable_Tabela;
    private javax.swing.JTextArea jTextArea_Descricao_Consulta;
    private javax.swing.JTextField jTextField_Pesquisa;
    // End of variables declaration//GEN-END:variables
}
