/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.github.projetolp2.view;

/**
 *
 * @author Guerreiro 3.0
 */
public class TelaSobreSDI extends javax.swing.JPanel {

    /**
     * Creates new form TelaSobreSDI2
     */
    public TelaSobreSDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_Salvar;
    private javax.swing.JLabel jLabel_Ano;
    private javax.swing.JLabel jLabel_Descricao_Do_Servico;
    private javax.swing.JLabel jLabel_Marca;
    private javax.swing.JLabel jLabel_Modelo;
    private javax.swing.JLabel jLabel_Placa;
    private javax.swing.JLabel jLabel_Proprietario;
    private javax.swing.JLabel jLabel_Telefone;
    private javax.swing.JPanel jPanel_Novo_Cadastro;
    private javax.swing.JScrollPane jScrollPane_Da_Descricao_Do_Servico;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField_Da_Marca;
    private javax.swing.JTextField jTextField_Da_Placa;
    private javax.swing.JTextField jTextField_Do_Ano;
    private javax.swing.JTextField jTextField_Do_Modelo;
    private javax.swing.JTextField jTextField_Do_Proprietario;
    private javax.swing.JTextField jTextField_Do_Telefone;
    // End of variables declaration//GEN-END:variables
}
