/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.github.projetolp2.view;

/**
 *
 * @author Guerreiro 3.0
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_TelaPrincipal = new javax.swing.JPanel();
        jLabel_Sistema_De_Cadastro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar_TelaPrincipal = new javax.swing.JMenuBar();
        jMenu_Arquivo = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu_Sobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_Sistema_De_Cadastro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_Sistema_De_Cadastro.setText("SISTEMA DE CADASTRO ");

        jLabel1.setText("Selecione uma opção no menu");

        javax.swing.GroupLayout jPanel_TelaPrincipalLayout = new javax.swing.GroupLayout(jPanel_TelaPrincipal);
        jPanel_TelaPrincipal.setLayout(jPanel_TelaPrincipalLayout);
        jPanel_TelaPrincipalLayout.setHorizontalGroup(
            jPanel_TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TelaPrincipalLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel_Sistema_De_Cadastro)
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TelaPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(115, 115, 115))
        );
        jPanel_TelaPrincipalLayout.setVerticalGroup(
            jPanel_TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TelaPrincipalLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel_Sistema_De_Cadastro)
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jMenu_Arquivo.setText("Arquivo");

        jMenuItem2.setText("Consultar Cadastros");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu_Arquivo.add(jMenuItem2);

        jMenuItem1.setText("Novo cadastro");
        jMenuItem1.addActionListener(this::jMenuItem_Novo_Cadastro_ActionPerformed);
        jMenu_Arquivo.add(jMenuItem1);

        jMenuItem3.setText("Alterar Cadastro");
        jMenu_Arquivo.add(jMenuItem3);

        jMenuItem4.setText("Excluir Cadastro");
        jMenu_Arquivo.add(jMenuItem4);

        jMenuBar_TelaPrincipal.add(jMenu_Arquivo);

        jMenu_Sobre.setText("Sobre");
        jMenu_Sobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_SobreMouseClicked(evt);
            }
        });
        jMenuBar_TelaPrincipal.add(jMenu_Sobre);

        setJMenuBar(jMenuBar_TelaPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_TelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_TelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_Novo_Cadastro_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Novo_Cadastro_ActionPerformed
    TelaCadastroSDI telaCadastro = new TelaCadastroSDI();
    getContentPane().removeAll();
    getContentPane().setLayout(new java.awt.BorderLayout()); 
    getContentPane().add(telaCadastro, java.awt.BorderLayout.CENTER); 
    revalidate();
    repaint();
    }//GEN-LAST:event_jMenuItem_Novo_Cadastro_ActionPerformed

    private void jMenu_SobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_SobreMouseClicked
    TelaSobreSDI telaSobre = new TelaSobreSDI();
    getContentPane().removeAll();
    getContentPane().setLayout(new java.awt.BorderLayout());
    getContentPane().add(telaSobre, java.awt.BorderLayout.CENTER); 
    revalidate();
    repaint();
    }//GEN-LAST:event_jMenu_SobreMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Sistema_De_Cadastro;
    private javax.swing.JMenuBar jMenuBar_TelaPrincipal;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu jMenu_Arquivo;
    private javax.swing.JMenu jMenu_Sobre;
    private javax.swing.JPanel jPanel_TelaPrincipal;
    // End of variables declaration//GEN-END:variables

    public void mostrarTelaInicial() {
        getContentPane().removeAll();
        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel_TelaPrincipal, java.awt.BorderLayout.CENTER);
        revalidate();
        repaint();
    }
}