/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.github.projetolp2.view;

import com.github.projetolp2.controller.VeiculoController;

/**
 *
 * @author Guerreiro 3.0
 */
public class TelaCadastroSDI extends javax.swing.JPanel {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastroSDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_Do_Proprietario1 = new javax.swing.JTextField();
        jTextField_Do_Ano1 = new javax.swing.JTextField();
        jTextField_Da_Marca1 = new javax.swing.JTextField();
        jLabel_Placa1 = new javax.swing.JLabel();
        jTextField_Da_Placa1 = new javax.swing.JTextField();
        jLabel_Modelo1 = new javax.swing.JLabel();
        jTextField_Do_Modelo1 = new javax.swing.JTextField();
        jLabel_Marca1 = new javax.swing.JLabel();
        jButton_Salvar1 = new javax.swing.JButton();
        jLabel_Ano1 = new javax.swing.JLabel();
        jButton_Cancelar1 = new javax.swing.JButton();
        jLabel_Proprietario1 = new javax.swing.JLabel();
        jScrollPane_Da_Descricao_Do_Servico1 = new javax.swing.JScrollPane();
        jTextArea_Descricao_Do_Servico = new javax.swing.JTextArea();
        jLabel_Telefone1 = new javax.swing.JLabel();
        jLabel_Descricao_Do_Servico1 = new javax.swing.JLabel();
        jTextField_Do_Telefone1 = new javax.swing.JTextField();

        jLabel_Placa1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Placa1.setText("Placa:");

        jLabel_Modelo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Modelo1.setText("Modelo:");

        jLabel_Marca1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Marca1.setText("Marca:");

        jButton_Salvar1.setText("Salvar");
        jButton_Salvar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Salvar1MouseClicked(evt);
            }
        });

        jLabel_Ano1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Ano1.setText("Ano:");

        jButton_Cancelar1.setText("Cancelar");
        jButton_Cancelar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Cancelar1MouseClicked(evt);
            }
        });

        jLabel_Proprietario1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Proprietario1.setText("Proprietário:");

        jTextArea_Descricao_Do_Servico.setColumns(20);
        jTextArea_Descricao_Do_Servico.setRows(5);
        jScrollPane_Da_Descricao_Do_Servico1.setViewportView(jTextArea_Descricao_Do_Servico);

        jLabel_Telefone1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Telefone1.setText("Telefone:");

        jLabel_Descricao_Do_Servico1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Descricao_Do_Servico1.setText("Descrição do serviço:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Descricao_Do_Servico1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Proprietario1)
                                    .addComponent(jButton_Salvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Do_Proprietario1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton_Cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane_Da_Descricao_Do_Servico1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel_Modelo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Do_Modelo1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel_Marca1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Da_Marca1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel_Placa1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Da_Placa1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Ano1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Do_Ano1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel_Telefone1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Do_Telefone1)))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Placa1)
                    .addComponent(jTextField_Da_Placa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Ano1)
                    .addComponent(jTextField_Do_Ano1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Modelo1)
                    .addComponent(jTextField_Do_Modelo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Marca1)
                    .addComponent(jTextField_Da_Marca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Proprietario1)
                    .addComponent(jTextField_Do_Proprietario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Do_Telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Telefone1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Descricao_Do_Servico1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_Da_Descricao_Do_Servico1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Cancelar1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButton_Salvar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Cancelar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Cancelar1MouseClicked
        java.awt.Window janela = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (janela instanceof TelaPrincipal principal ) {
            principal.mostrarTelaInicial();
        }
    }//GEN-LAST:event_jButton_Cancelar1MouseClicked

    private void jButton_Salvar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Salvar1MouseClicked
/*
        VeiculoController controller = new VeiculoController();

        String erro = controller.cadastrarVeiculo(
            jTextField_Da_Placa1.getText(),
            jTextField_Do_Modelo1.getText(),
            jTextField_Da_Marca1.getText(),
            jTextField_Do_Ano1.getText(),
            jTextField_Do_Proprietario1.getText(),
           jTextField_Do_Telefone1.getText(),
            jTextArea_Descricao_Do_Servico.getText()
        );     


        if (erro == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Veículo cadastrado com sucesso!",
                "Sucesso", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            limparCampos();

            java.awt.Window janela = javax.swing.SwingUtilities.getWindowAncestor(this);
            if (janela instanceof com.github.projetolp2.view.TelaPrincipal) {
                ((com.github.projetolp2.view.TelaPrincipal) janela).mostrarTelaInicial();
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                erro, "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
*/
    }//GEN-LAST:event_jButton_Salvar1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancelar1;
    private javax.swing.JButton jButton_Salvar1;
    private javax.swing.JLabel jLabel_Ano1;
    private javax.swing.JLabel jLabel_Descricao_Do_Servico1;
    private javax.swing.JLabel jLabel_Marca1;
    private javax.swing.JLabel jLabel_Modelo1;
    private javax.swing.JLabel jLabel_Placa1;
    private javax.swing.JLabel jLabel_Proprietario1;
    private javax.swing.JLabel jLabel_Telefone1;
    private javax.swing.JScrollPane jScrollPane_Da_Descricao_Do_Servico1;
    private javax.swing.JTextArea jTextArea_Descricao_Do_Servico;
    private javax.swing.JTextField jTextField_Da_Marca1;
    private javax.swing.JTextField jTextField_Da_Placa1;
    private javax.swing.JTextField jTextField_Do_Ano1;
    private javax.swing.JTextField jTextField_Do_Modelo1;
    private javax.swing.JTextField jTextField_Do_Proprietario1;
    private javax.swing.JTextField jTextField_Do_Telefone1;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
        jTextField_Da_Placa1.setText("");
        jTextField_Do_Modelo1.setText("");
        jTextField_Da_Marca1.setText("");
        jTextField_Do_Ano1.setText("");
        jTextField_Do_Proprietario1.setText("");
        jTextField_Do_Telefone1.setText("");
        jTextArea_Descricao_Do_Servico.setText(""); 
    }
}
