/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.github.projetolp2.view.mdi;

import com.github.projetolp2.controller.VeiculoController;
import com.github.projetolp2.model.Veiculo;
import com.github.projetolp2.view.sdi.TelaConsultarSDI;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guerreiro 3.0
 */
public class TelaConsultarMDI extends javax.swing.JInternalFrame {

    private final VeiculoController controller = new VeiculoController();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaConsultarMDI.class.getName());
    public TelaConsultarMDI() {
        initComponents();
        configurarTabela();
        configurarSelecaoTabela();
        configurarPlaceholder();
        setClosable(true);
        setMaximizable(true);
        setIconifiable(true);
        setResizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_Selecionar = new javax.swing.ButtonGroup();
        jPanel_Criterio = new javax.swing.JPanel();
        jRadioButton_Modelo = new javax.swing.JRadioButton();
        jRadioButton_Proprietario = new javax.swing.JRadioButton();
        jLabel_PesquisarPor = new javax.swing.JLabel();
        jRadioButton_Placa = new javax.swing.JRadioButton();
        jRadioButton_Codigo = new javax.swing.JRadioButton();
        jPanel_Termo = new javax.swing.JPanel();
        jButton_Pesquisar = new javax.swing.JButton();
        jLabel_DigiteAqui = new javax.swing.JLabel();
        jTextField_Pesquisa = new javax.swing.JTextField();
        jPanel_Tabela = new javax.swing.JPanel();
        jScrollPane_Tabela = new javax.swing.JScrollPane();
        jTable_Tabela = new javax.swing.JTable();
        jPanel_Descricao = new javax.swing.JPanel();
        jScrollPane_Descricao = new javax.swing.JScrollPane();
        jTextArea_Descricao_Consulta = new javax.swing.JTextArea();
        jLabel_Descricao = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton_Excluir = new javax.swing.JButton();
        jButton_Alterar = new javax.swing.JButton();

        buttonGroup_Selecionar.add(jRadioButton_Modelo);
        jRadioButton_Modelo.setText("Modelo");
        jRadioButton_Modelo.addActionListener(this::jRadioButton_ModeloActionPerformed);

        buttonGroup_Selecionar.add(jRadioButton_Proprietario);
        jRadioButton_Proprietario.setText("Proprietário");

        jLabel_PesquisarPor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_PesquisarPor.setText("Pesquisar por:");

        buttonGroup_Selecionar.add(jRadioButton_Placa);
        jRadioButton_Placa.setText("Placa");

        buttonGroup_Selecionar.add(jRadioButton_Codigo);
        jRadioButton_Codigo.setText("Código");

        javax.swing.GroupLayout jPanel_CriterioLayout = new javax.swing.GroupLayout(jPanel_Criterio);
        jPanel_Criterio.setLayout(jPanel_CriterioLayout);
        jPanel_CriterioLayout.setHorizontalGroup(
            jPanel_CriterioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CriterioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_PesquisarPor)
                .addGap(12, 12, 12)
                .addComponent(jRadioButton_Codigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_Placa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_Modelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_Proprietario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_CriterioLayout.setVerticalGroup(
            jPanel_CriterioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CriterioLayout.createSequentialGroup()
                .addGroup(jPanel_CriterioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_PesquisarPor)
                    .addComponent(jRadioButton_Placa)
                    .addComponent(jRadioButton_Modelo)
                    .addComponent(jRadioButton_Proprietario)
                    .addComponent(jRadioButton_Codigo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_Pesquisar.setText("Pesquisar");
        jButton_Pesquisar.addActionListener(this::jButton_PesquisarActionPerformed);

        jLabel_DigiteAqui.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_DigiteAqui.setText("Digite aqui:");

        jTextField_Pesquisa.setToolTipText("Deixe em branco para listar todos os veículos");
        jTextField_Pesquisa.addActionListener(this::jTextField_PesquisaActionPerformed);

        javax.swing.GroupLayout jPanel_TermoLayout = new javax.swing.GroupLayout(jPanel_Termo);
        jPanel_Termo.setLayout(jPanel_TermoLayout);
        jPanel_TermoLayout.setHorizontalGroup(
            jPanel_TermoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TermoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_DigiteAqui)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_TermoLayout.setVerticalGroup(
            jPanel_TermoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TermoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_TermoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_DigiteAqui)
                    .addComponent(jTextField_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable_Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Proprietário", "Telefone", "Placa", "Modelo", "Marca", "Ano", "Descrição"
            }
        ));
        jScrollPane_Tabela.setViewportView(jTable_Tabela);

        jTextArea_Descricao_Consulta.setEditable(false);
        jTextArea_Descricao_Consulta.setColumns(20);
        jTextArea_Descricao_Consulta.setLineWrap(true);
        jTextArea_Descricao_Consulta.setRows(5);
        jScrollPane_Descricao.setViewportView(jTextArea_Descricao_Consulta);

        jLabel_Descricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Descricao.setText("Descrição:");

        javax.swing.GroupLayout jPanel_DescricaoLayout = new javax.swing.GroupLayout(jPanel_Descricao);
        jPanel_Descricao.setLayout(jPanel_DescricaoLayout);
        jPanel_DescricaoLayout.setHorizontalGroup(
            jPanel_DescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DescricaoLayout.createSequentialGroup()
                .addComponent(jLabel_Descricao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane_Descricao)
        );
        jPanel_DescricaoLayout.setVerticalGroup(
            jPanel_DescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DescricaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_TabelaLayout = new javax.swing.GroupLayout(jPanel_Tabela);
        jPanel_Tabela.setLayout(jPanel_TabelaLayout);
        jPanel_TabelaLayout.setHorizontalGroup(
            jPanel_TabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TabelaLayout.createSequentialGroup()
                .addGroup(jPanel_TabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane_Tabela, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Descricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_TabelaLayout.setVerticalGroup(
            jPanel_TabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TabelaLayout.createSequentialGroup()
                .addComponent(jScrollPane_Tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton_Excluir.setText("Excluir");
        jButton_Excluir.addActionListener(this::jButton_ExcluirActionPerformed);

        jButton_Alterar.setText("Alterar");
        jButton_Alterar.addActionListener(this::jButton_AlterarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel_Criterio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Tabela, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel_Termo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Criterio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Termo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Tabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void configurarPlaceholder() {
    String placeholder = "Deixe em branco para listar todos";

    jTextField_Pesquisa.setText(placeholder);
    jTextField_Pesquisa.setForeground(Color.GRAY);

    jTextField_Pesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (jTextField_Pesquisa.getText().equals(placeholder)) {
                jTextField_Pesquisa.setText("");
                jTextField_Pesquisa.setForeground(Color.BLACK);
            }
        }

        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (jTextField_Pesquisa.getText().isBlank()) {
                jTextField_Pesquisa.setText(placeholder);
                jTextField_Pesquisa.setForeground(Color.GRAY);
            }
        }
    });
}
    private void jButton_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PesquisarActionPerformed
        String termo = jTextField_Pesquisa.getText().trim();
        String criterio;

        if (termo.equals("Deixe em branco para listar todos")) {
            //Para permitir pesquisa "global"
            termo = "";
        }

        if (termo.isBlank()) {
            criterio = "todos";
        } else if (jRadioButton_Placa.isSelected()) {
            criterio = "placa";
        } else if (jRadioButton_Modelo.isSelected()) {
            criterio = "modelo";
        } else if (jRadioButton_Proprietario.isSelected()) {
            criterio = "proprietario";
        } else if (jRadioButton_Codigo.isSelected()) {
            criterio = "codigo";
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um critério de busca.");
            return;
        }

        List<Veiculo> resultado = controller.consultar(termo, criterio);

        DefaultTableModel modelo = (DefaultTableModel) jTable_Tabela.getModel();
        modelo.setRowCount(0);

        if (resultado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum veículo encontrado.\nVerifique a busca");
            return;
        }

        for (Veiculo v : resultado) {
            modelo.addRow(new Object[]{
                v.getCodigo(),
                v.getProprietario(),
                v.getTelefoneProprietario(),
                v.getPlaca(),
                v.getModelo(),
                v.getMarca(),
                v.getAno(),
                v.getDescricaoServico()
            });
        }
    }//GEN-LAST:event_jButton_PesquisarActionPerformed

    private void jTextField_PesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PesquisaActionPerformed

    private void jButton_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExcluirActionPerformed
        //Cria a tela de exlcuir
        int linhaSelecionada = jTable_Tabela.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um veículo na tabela.");
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) jTable_Tabela.getModel();

        Veiculo veiculo = new Veiculo(
            (int) modelo.getValueAt(linhaSelecionada, 0),
            (String) modelo.getValueAt(linhaSelecionada, 3),
            (String) modelo.getValueAt(linhaSelecionada, 4),
            (String) modelo.getValueAt(linhaSelecionada, 5),
            (int) modelo.getValueAt(linhaSelecionada, 6),
            (String) modelo.getValueAt(linhaSelecionada, 1),
            (String) modelo.getValueAt(linhaSelecionada, 2),
            (String) modelo.getValueAt(linhaSelecionada, 7)
        );

        TelaExcluirMDI telaExcluir = new TelaExcluirMDI(veiculo);
        getDesktopPane().add(telaExcluir); 
        telaExcluir.setVisible(true);
    }//GEN-LAST:event_jButton_ExcluirActionPerformed

    private void jButton_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AlterarActionPerformed
        //Pegando qual linha esta clicada
        int linhaSelecionada = jTable_Tabela.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um veículo na tabela.");
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) jTable_Tabela.getModel();

        Veiculo veiculo = new Veiculo(
            (int) modelo.getValueAt(linhaSelecionada, 0),
            (String) modelo.getValueAt(linhaSelecionada, 3),
            (String) modelo.getValueAt(linhaSelecionada, 4),
            (String) modelo.getValueAt(linhaSelecionada, 5),
            (int) modelo.getValueAt(linhaSelecionada, 6),
            (String) modelo.getValueAt(linhaSelecionada, 1),
            (String) modelo.getValueAt(linhaSelecionada, 2),
            (String) modelo.getValueAt(linhaSelecionada, 7)
        );

        TelaAlterarMDI telaCadastro = new TelaAlterarMDI(veiculo);
        getDesktopPane().add(telaCadastro);
        telaCadastro.setVisible(true);

    }//GEN-LAST:event_jButton_AlterarActionPerformed

    private void jRadioButton_ModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_ModeloActionPerformed
  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaConsultarSDI().setVisible(true));
    }
    
    //Praticamente pega a tabela e torna ela impossível de ser editada
    private void configurarTabela() {
        DefaultTableModel modeloAtual = (DefaultTableModel) jTable_Tabela.getModel();

        DefaultTableModel modeloNaoEditavel = new DefaultTableModel(
            new Object[]{"Código", "Proprietário", "Telefone", "Placa", "Modelo", "Marca", "Ano", "Descrição"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        jTable_Tabela.setModel(modeloNaoEditavel);
    }
    
    private void configurarSelecaoTabela() {
        jTable_Tabela.getSelectionModel().addListSelectionListener(evt -> {
            int linhaSelecionada = jTable_Tabela.getSelectedRow();
            if (linhaSelecionada != -1) {
                DefaultTableModel modelo = (DefaultTableModel) jTable_Tabela.getModel();
                jTextArea_Descricao_Consulta.setText(
                    (String) modelo.getValueAt(linhaSelecionada, 7)
                );
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_Selecionar;
    private javax.swing.JButton jButton_Alterar;
    private javax.swing.JButton jButton_Excluir;
    private javax.swing.JButton jButton_Pesquisar;
    private javax.swing.JLabel jLabel_Descricao;
    private javax.swing.JLabel jLabel_DigiteAqui;
    private javax.swing.JLabel jLabel_PesquisarPor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Criterio;
    private javax.swing.JPanel jPanel_Descricao;
    private javax.swing.JPanel jPanel_Tabela;
    private javax.swing.JPanel jPanel_Termo;
    private javax.swing.JRadioButton jRadioButton_Codigo;
    private javax.swing.JRadioButton jRadioButton_Modelo;
    private javax.swing.JRadioButton jRadioButton_Placa;
    private javax.swing.JRadioButton jRadioButton_Proprietario;
    private javax.swing.JScrollPane jScrollPane_Descricao;
    private javax.swing.JScrollPane jScrollPane_Tabela;
    private javax.swing.JTable jTable_Tabela;
    private javax.swing.JTextArea jTextArea_Descricao_Consulta;
    private javax.swing.JTextField jTextField_Pesquisa;
    // End of variables declaration//GEN-END:variables
}
