/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.github.projetolp2.view.mdi;

import com.github.projetolp2.view.sdi.TelaSobreSDI;

/**
 *
 * @author Guerreiro 3.0
 */
public class TelaPrincipalMDI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipalMDI.class.getName());

    /**
     * Creates new form TelaPrincipalMDI
     */
    public TelaPrincipalMDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar_TelaPrincipalMDI = new javax.swing.JMenuBar();
        jMenu_Arquivo = new javax.swing.JMenu();
        jMenuItem_Consultar = new javax.swing.JMenuItem();
        jMenuItem_Cadastrar = new javax.swing.JMenuItem();
        jMenu_Sobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 859, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        jMenu_Arquivo.setText("Arquivo");

        jMenuItem_Consultar.setText("Consultar Cadastros");
        jMenuItem_Consultar.addActionListener(this::jMenuItem_ConsultarActionPerformed);
        jMenu_Arquivo.add(jMenuItem_Consultar);

        jMenuItem_Cadastrar.setText("Novo cadastro");
        jMenuItem_Cadastrar.addActionListener(this::jMenuItem_CadastrarActionPerformed);
        jMenu_Arquivo.add(jMenuItem_Cadastrar);

        jMenuBar_TelaPrincipalMDI.add(jMenu_Arquivo);

        jMenu_Sobre.setText("Sobre");
        jMenu_Sobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_SobreMouseClicked(evt);
            }
        });
        jMenuBar_TelaPrincipalMDI.add(jMenu_Sobre);

        setJMenuBar(jMenuBar_TelaPrincipalMDI);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ConsultarActionPerformed
        TelaConsultarMDI telaConsultar = new TelaConsultarMDI();
        jDesktopPane1.add(telaConsultar);
        telaConsultar.setVisible(true);
        telaConsultar.moveToFront();
        try {
            telaConsultar.setSelected(true);
        } catch (java.beans.PropertyVetoException ex) {}
    }//GEN-LAST:event_jMenuItem_ConsultarActionPerformed

    private void jMenuItem_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CadastrarActionPerformed
        TelaCadastroMDI telaCadastrar = new TelaCadastroMDI();
        jDesktopPane1.add(telaCadastrar);
        telaCadastrar.setVisible(true);
        telaCadastrar.moveToFront();
        try {
            telaCadastrar.setSelected(true);
        } catch (java.beans.PropertyVetoException ex) {}
    }//GEN-LAST:event_jMenuItem_CadastrarActionPerformed

    private void jMenu_SobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_SobreMouseClicked
        TelaSobreMDI telaSobre = new TelaSobreMDI();
        jDesktopPane1.add(telaSobre); 
        telaSobre.setVisible(true);
    }//GEN-LAST:event_jMenu_SobreMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipalMDI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar_TelaPrincipalMDI;
    private javax.swing.JMenuItem jMenuItem_Cadastrar;
    private javax.swing.JMenuItem jMenuItem_Consultar;
    private javax.swing.JMenu jMenu_Arquivo;
    private javax.swing.JMenu jMenu_Sobre;
    // End of variables declaration//GEN-END:variables

}
