/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.github.projetolp2.view.sdi;

import com.github.projetolp2.controller.ResultadoOperacao;
import com.github.projetolp2.controller.VeiculoController;
import com.github.projetolp2.model.Veiculo;
import javax.swing.JOptionPane;

/**
 *
 * @author rick
 */
public class TelaAlterarSDI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAlterarSDI.class.getName());
    
    private final VeiculoController controller = new VeiculoController();
    private Veiculo veiculoEmEdicao;
    
    /**
     * Creates new form TelaUsadaSDI
     */
    public TelaAlterarSDI() {
        initComponents();
    }
    
    public TelaAlterarSDI(Veiculo veiculo) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        this.veiculoEmEdicao = veiculo;
        preencherCampos(veiculo);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Cima = new javax.swing.JPanel();
        jLabel_Ano1 = new javax.swing.JLabel();
        jTextField_Do_Ano1 = new javax.swing.JTextField();
        jLabel_Placa1 = new javax.swing.JLabel();
        jTextField_Da_Placa1 = new javax.swing.JTextField();
        jLabel_Telefone1 = new javax.swing.JLabel();
        jTextField_Do_Telefone1 = new javax.swing.JTextField();
        jLabel_Proprietario1 = new javax.swing.JLabel();
        jTextField_Do_Proprietario1 = new javax.swing.JTextField();
        jTextField_Da_Marca1 = new javax.swing.JTextField();
        jLabel_Modelo1 = new javax.swing.JLabel();
        jTextField_Do_Modelo1 = new javax.swing.JTextField();
        jLabel_Marca1 = new javax.swing.JLabel();
        jPanelDescricao = new javax.swing.JPanel();
        jLabel_Descricao_Do_Servico1 = new javax.swing.JLabel();
        jScrollPane_Da_Descricao_Do_Servico1 = new javax.swing.JScrollPane();
        jTextArea_Descricao_Do_Servico = new javax.swing.JTextArea();
        jPanel_Inferior = new javax.swing.JPanel();
        jButton_Cancelar1 = new javax.swing.JButton();
        jButton_Salvar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Alterar");

        jLabel_Ano1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Ano1.setText("Ano:");

        jLabel_Placa1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Placa1.setText("Placa:");

        jLabel_Telefone1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Telefone1.setText("Telefone:");

        jLabel_Proprietario1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Proprietario1.setText("Proprietário:");

        jLabel_Modelo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Modelo1.setText("Modelo:");

        jLabel_Marca1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Marca1.setText("Marca:");

        javax.swing.GroupLayout jPanel_CimaLayout = new javax.swing.GroupLayout(jPanel_Cima);
        jPanel_Cima.setLayout(jPanel_CimaLayout);
        jPanel_CimaLayout.setHorizontalGroup(
            jPanel_CimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CimaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_CimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_CimaLayout.createSequentialGroup()
                        .addComponent(jLabel_Proprietario1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Do_Proprietario1))
                    .addGroup(jPanel_CimaLayout.createSequentialGroup()
                        .addComponent(jLabel_Marca1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Da_Marca1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CimaLayout.createSequentialGroup()
                        .addComponent(jLabel_Telefone1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Do_Telefone1))
                    .addGroup(jPanel_CimaLayout.createSequentialGroup()
                        .addComponent(jLabel_Modelo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Do_Modelo1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CimaLayout.createSequentialGroup()
                        .addComponent(jLabel_Placa1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Da_Placa1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Ano1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Do_Ano1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_CimaLayout.setVerticalGroup(
            jPanel_CimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CimaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_CimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_CimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_Placa1)
                        .addComponent(jTextField_Da_Placa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_Ano1))
                    .addComponent(jTextField_Do_Ano1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_CimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Do_Telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Telefone1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_CimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Modelo1)
                    .addComponent(jTextField_Do_Modelo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_CimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Marca1)
                    .addComponent(jTextField_Da_Marca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_CimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Proprietario1)
                    .addComponent(jTextField_Do_Proprietario1))
                .addContainerGap())
        );

        jLabel_Descricao_Do_Servico1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Descricao_Do_Servico1.setText("Descrição do serviço:");

        jTextArea_Descricao_Do_Servico.setColumns(20);
        jTextArea_Descricao_Do_Servico.setLineWrap(true);
        jTextArea_Descricao_Do_Servico.setRows(5);
        jScrollPane_Da_Descricao_Do_Servico1.setViewportView(jTextArea_Descricao_Do_Servico);

        javax.swing.GroupLayout jPanelDescricaoLayout = new javax.swing.GroupLayout(jPanelDescricao);
        jPanelDescricao.setLayout(jPanelDescricaoLayout);
        jPanelDescricaoLayout.setHorizontalGroup(
            jPanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane_Da_Descricao_Do_Servico1)
            .addGroup(jPanelDescricaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Descricao_Do_Servico1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDescricaoLayout.setVerticalGroup(
            jPanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDescricaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Descricao_Do_Servico1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_Da_Descricao_Do_Servico1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton_Cancelar1.setText("Cancelar");
        jButton_Cancelar1.addActionListener(this::jButton_Cancelar1ActionPerformed);

        jButton_Salvar1.setText("Salvar");
        jButton_Salvar1.addActionListener(this::jButton_Salvar1ActionPerformed);

        javax.swing.GroupLayout jPanel_InferiorLayout = new javax.swing.GroupLayout(jPanel_Inferior);
        jPanel_Inferior.setLayout(jPanel_InferiorLayout);
        jPanel_InferiorLayout.setHorizontalGroup(
            jPanel_InferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Salvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_InferiorLayout.setVerticalGroup(
            jPanel_InferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_InferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Salvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel_Cima, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Inferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Cima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Inferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cancelar1ActionPerformed
        //Somente fecha a tela
        dispose();
    }//GEN-LAST:event_jButton_Cancelar1ActionPerformed

    private void jButton_Salvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Salvar1ActionPerformed
       try {
            int ano = Integer.parseInt(jTextField_Do_Ano1.getText().trim());

            Veiculo veiculo = new Veiculo(
                veiculoEmEdicao == null ? 0 : veiculoEmEdicao.getCodigo(),
                jTextField_Da_Placa1.getText().trim(),
                jTextField_Do_Modelo1.getText().trim(),
                jTextField_Da_Marca1.getText().trim(),
                ano,
                jTextField_Do_Proprietario1.getText().trim(),
                jTextField_Do_Telefone1.getText().trim(),
                jTextArea_Descricao_Do_Servico.getText().trim()
            );

            ResultadoOperacao resultado = (veiculoEmEdicao == null)
                    ? controller.cadastrar(veiculo)
                    : controller.editar(veiculo);

            if (resultado.isSucesso()) {
                JOptionPane.showMessageDialog(this, resultado.getMensagem());
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, resultado.getMensagem(), "Erro", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ano inválido.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_Salvar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaAlterarSDI().setVisible(true));
    }

    private void preencherCampos(Veiculo veiculo) {
        jTextField_Da_Placa1.setText(veiculo.getPlaca());
        jTextField_Do_Modelo1.setText(veiculo.getModelo());
        jTextField_Da_Marca1.setText(veiculo.getMarca());
        jTextField_Do_Ano1.setText(String.valueOf(veiculo.getAno()));
        jTextField_Do_Proprietario1.setText(veiculo.getProprietario());
        jTextField_Do_Telefone1.setText(veiculo.getTelefoneProprietario());
        jTextArea_Descricao_Do_Servico.setText(veiculo.getDescricaoServico());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancelar1;
    private javax.swing.JButton jButton_Salvar1;
    private javax.swing.JLabel jLabel_Ano1;
    private javax.swing.JLabel jLabel_Descricao_Do_Servico1;
    private javax.swing.JLabel jLabel_Marca1;
    private javax.swing.JLabel jLabel_Modelo1;
    private javax.swing.JLabel jLabel_Placa1;
    private javax.swing.JLabel jLabel_Proprietario1;
    private javax.swing.JLabel jLabel_Telefone1;
    private javax.swing.JPanel jPanelDescricao;
    private javax.swing.JPanel jPanel_Cima;
    private javax.swing.JPanel jPanel_Inferior;
    private javax.swing.JScrollPane jScrollPane_Da_Descricao_Do_Servico1;
    private javax.swing.JTextArea jTextArea_Descricao_Do_Servico;
    private javax.swing.JTextField jTextField_Da_Marca1;
    private javax.swing.JTextField jTextField_Da_Placa1;
    private javax.swing.JTextField jTextField_Do_Ano1;
    private javax.swing.JTextField jTextField_Do_Modelo1;
    private javax.swing.JTextField jTextField_Do_Proprietario1;
    private javax.swing.JTextField jTextField_Do_Telefone1;
    // End of variables declaration//GEN-END:variables
}
